### PR TITLE
fix: restore double-click to copy account ID and hide account ID from row

### LINKED ISSUE #239: [v5.9.4 Issues] UI layout broken on non-100% DPI & Performance issues in HK region
## [Bug Report] v5.9.4 使用者回報問題彙整（2026-04-22）

> 以下問題來自巴哈姆特新楓之谷板的用戶回報（2026/04/22 08:00 後）及 GitHub issue #238。

---

### 問題一：點擊兩下複製帳號功能消失 (Done in #244)

**回報者：** 資深老邦寶（巴哈留言 B22）
**時間：** 2026-04-22 20:57

**問題描述：**
舊版中可雙擊帳號列直接複製帳號的功能，在 v5.9.4 中已消失。

**預期行為：**
雙擊帳號列 → 自動複製帳號密碼

**實際行為：**
雙擊無反應，功能不見了

---

### 問題二：UI 版面在系統縮放／DPI 非 100% 時無法完整呈現

> 關聯 issue #238，合併追蹤。

**問題描述：**
當系統文字縮放比例或 DPI 不為 100% 時，v5.9.4 版面無法完整呈現，部分按鈕超出可視範圍而無法點擊。以下三個情況均有回報，行為一致。

**情況 A：控制台 > 協助工具 > 文字大小調整（關聯 #238）**
- 路徑：控制台 > 協助工具 > 文字大小
- 將文字大小調大（例如 4K 螢幕設為 150%）
- 結果：版面無法完整呈現

**情況 B：Windows 顯示縮放設為 125%**
- 路徑：設定 > 顯示 > 縮放與版面配置 > 125%
- 結果：介面顯示異常

**附圖（情況 B）：**
縮放125%截圖

**情況 C：筆電螢幕 — 設定頁面過大，返回按鈕按不到**
- 進入設定頁面後，畫面超出筆電螢幕可視範圍
- 返回按鈕位於畫面下方，無法點擊

**附圖（情況 C）：**
設定頁面截圖

**預期行為：**
無論系統縮放比例為何，UI 應能正常呈現，所有按鈕均可點擊。

**建議修復方向：**
- 偵測系統 DPI / 縮放比例並動態調整版面
- 設定頁面加入捲動支援，確保按鈕在低解析度或高縮放下仍可存取
- 參考 WebView2 的 `SetZoomFactor` 或 Tauri 的視窗縮放 API

**回報者：**

| 回報者 | 來源 | 時間 |
|--------|------|------|
| issue #238 | GitHub | — |
| ペンドラゴン | 巴哈姆特 B21 | 2026-04-22 17:53 |
| 冰浦蒼士 | 巴哈姆特 5樓 | 2026-04-23 |

---

### 💬 UX 建議（非 bug，但影響使用體驗）

1. **視窗整體過大**（秋楓 B8/B9、小胖森 B11，2026-04-22 09:38–11:40）
   - 整體 UI 比舊版大很多，希望縮小至接近舊版尺寸
   - 建議提供視窗大小調整或縮放選項
   - 注：與問題二高度相關，可考慮一併處理

2. **字體大小自由調整**（夢想乂翼 B25）
   - 建議在設定中新增字體大小選單，方便不同需求用戶

---

### 資料來源

巴哈姆特論壇：https://forum.gamer.com.tw/C.php?bsn=7650&snA=1036832

### PR DESCRIPTION
**Pull request by YCC3741**
## Summary

- **Restore double-click to copy account ID**: Add `@dblclick` handler on account rows that copies the row's service-account ID (`a.sid`) to the clipboard via `navigator.clipboard.writeText`, mirroring the WPF `lstViewAccount_MouseDoubleClick` behaviour (`Clipboard.SetText(selected.sid)`) reported missing in [#239](https://github.com/pungin/Beanfun/issues/239) (問題一). The existing i18n key `DoubleClickCopy` ("雙擊複製帳號" / "Double-click to copy account") already documents this WPF semantic.
- **Hide account ID from row**: Remove the `ID: xxx` subtitle from account rows, showing only the account display name. Banned status text is preserved.

## Changes

- `src/pages/AccountList.vue`:
  - New `handleRowDblClick(a)` async handler:
    - Banned-row guard (`if (!a.is_enable) return`) preserved
    - `await navigator.clipboard.writeText(a.sid)` then `ElMessage.success(t('CopyFinished'))`
    - On clipboard rejection (permission / trust-boundary) → `ElMessage.error(t('CopyFailed'))`
    - Does **not** mutate `account.selectedSid` and does **not** call `handleGetOtp()` — those belong to the single-click + Enter / Get OTP button path
  - Bind `@dblclick` on each account row
  - Remove ID display from row subtitle; keep banned-status text only
- `tests/unit/pages/AccountList.spec.ts`:
  - `'double-clicking an enabled row...'` now asserts `clipboard.writeText('sid-2')` + `CopyFinished` toast, and that `commands.getOtp` was **not** called and `account.selectedSid` was **not** mutated
  - `'double-clicking a banned row...'` asserts `clipboard.writeText` was not called

## Test plan

- Double-click an enabled account row → row's account ID is copied to clipboard, "複製完成" toast appears
- Double-click a banned account row → nothing happens (no clipboard write, no toast)
- Account rows display only the name, no ID subtitle
- Banned rows still show the locked status text
- Single-click still selects the row normally
- Enter hotkey still triggers Get OTP after row selection
- Selection state (e.g. from PR #245 auto-select) is preserved across double-click

## Local verification

- `npm test` → 41 files / 599 tests passed
- `npm run typecheck` → passes
- Branch rebased onto latest `code` (incorporates #245, #250, #251, #252, #253) — no conflicts

Closes #239

### CODE REVIEW

**Comment by lshw54** [comment]
The double-click handler is wiring up the wrong action. According to issue #239, the original WPF `lstViewAccount_MouseDoubleClick` behaviour was to copy the service account ID (`a.sid`) to the clipboard — not to fetch and copy the OTP.
`handleRowDblClick` should be simplified to just copy `a.sid` directly.

The `handleGetOtp()` call should be removed entirely from this handler. Please also update the PR title, summary, and test plan accordingly — the test currently asserts that `commands.getOtp` is called on double-click, which would no longer be the expected behaviour.

File: src/pages/AccountList.vue [hunk 1]
```diff
@@ -286,6 +286,18 @@ function selectRow(a: ServiceAccount): void {
...
+/**
+ * Double-click on a row → select + fetch OTP + copy to clipboard.
+ * Mirrors WPF `lstViewAccount_MouseDoubleClick` which called
+ * `btnGetOtp_Click` on the double-clicked row. Banned rows are
+ * ignored (same guard as {@link selectRow}).
+ */
+function handleRowDblClick(a: ServiceAccount): void {
+  if (!a.is_enable) return
+  account.selectedSid = a.sid
+  void handleGetOtp()
```
Comment (lshw54) [inline src/pages/AccountList.vue]: Replace `void handleGetOtp()` with `navigator.clipboard.writeText(a.sid)` + success toast

File: tests/unit/pages/AccountList.spec.ts [hunk 2]
```diff
@@ -917,6 +917,49 @@ describe('AccountList page', () => {
     expect(account.selectedSid).toBeNull()
   })
 
+  it('double-clicking an enabled row arms selection and fetches OTP (WPF parity, issue #239)', async () => {
```
Comment (lshw54) [inline tests/unit/pages/AccountList.spec.ts]: Assert `clipboard.writeText` called with `a.sid`, not `commands.getOtp`

**Review by lshw54 — CHANGES_REQUESTED** [review]

**Comment by lshw54** [comment]
Please also note that #248, #250, #251, #252 and #253 is already merge, make sure to review and incorporate those changes before merging this PR to avoid any conflicts.

**Review by lshw54 — APPROVED** [review]
All good now!
